version: '3.1'
services:
  eureka:
    image: albinxavier/naming-server
    ports:
      - "8761:8761"
     
  student:
    image: albinxavier/student-service   
    ports:
      - "9991:9991"
    depends_on:
      - book
      - eureka
  book:
    image: albinxavier/book-service
    ports:
      - "9992:9992"
    depends_on:
      - postgresqldb
      - eureka
 
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
